### ISSUE TITLE
problem installing snips on windows

### ISSUE THREAD

**Issue by hvaneylen** [snipsco/snips-nlu#549]
After installing Visual Studio 2017 and Rust, I finally ran pip install snips-nlu and the following error was displayed 
error[E0425]: cannot find function `parse_crate` in module `syn`
     --> C:\Users\jhg\.cargo\registry\src\github.com-1ecc6299db9ec823\cbindgen-0.4.3\src\bindgen\parser.rs:167:30

What can I do ?

**Comment by adrienball** [comment]
Hi @hvaneylen , thanks for reporting this issue,
We are aware of it, it should be fixed in the next release (probably `0.12.2`) coming soon, I'll keep you posted.

**Comment by hvaneylen** [comment]
Hi Adrien,

Thanks for the upgrade – it goes one step further but still failed
Compiling snips-nlu-utils-py v0.6.0 (file:///C:/Users/HVANEY~1/AppData/Local/Temp/pip-build-ss7007sn/snips-nlu-utils/snips_nlu_utils_py)
 error: linking with `link.exe` failed: exit code: 1120

Any idea of what’s going wrong ?

Cheers


De : Adrien Ball [mailto:notifications@github.com]
Envoyé : vendredi 6 avril 2018 14:49
À : snipsco/snips-nlu <snips-nlu@noreply.github.com>
Cc : Hugues Van Eylen <hvaneylen@sodifrance.fr>; Mention <mention@noreply.github.com>
Objet : Re: [snipsco/snips-nlu] problem installing snips on windows (#549)


Hi @hvaneylen<https://github.com/hvaneylen>,
We just released 0.13.0, can you try to run: pip install snips-nlu==0.13.0 and tell us if it works?
Cheers

**Comment by adrienball** [comment]
Hi @hvaneylen, I'll investigate this next week.
We are currently targeting Linux and MacOS platforms. For other platforms, we provide source distribution so you can build from source, but we haven't tested it. I'll try to setup a windows environment to debug the issues you're having, will keep you posted.

Cheers

**Comment by adrienball** [comment]
Hi @hvaneylen,
can you run `export RUST_BACKTRACE=1`, re-run the pip install and share the backtrace here?
Thanks, also what is your version of Rust?

**Comment by adrienball** [comment]
Hey @hvaneylen ,
I'm following up on this issue we now have pre-compiled wheels for the target win_amd64, for snips-nlu's dependencies, making the installation process on windows much faster/simpler.
It would be great, if you could try to install the latest version of snips-nlu (0.15.1) and check if everything works fine 😉

Cheers!
Adrien

**Comment by hvaneylen** [comment]
Hi Adrien,

I will try this as soon as I will be back from holidays and check if I can use snips on windows.
Thanks
Hugues

De : Adrien Ball <notifications@github.com>
Envoyé : lundi 9 juillet 2018 16:05
À : snipsco/snips-nlu <snips-nlu@noreply.github.com>
Cc : Hugues Van Eylen <hvaneylen@sodifrance.fr>; Mention <mention@noreply.github.com>
Objet : Re: [snipsco/snips-nlu] problem installing snips on windows (#549)


Hey @hvaneylen<https://github.com/hvaneylen> ,
I'm following up on this issue we now have pre-compiled wheels for the target win_amd64, for snips-nlu's dependencies, making the installation process on windows much faster/simpler.
It would be great, if you could try to install the latest version of snips-nlu (0.15.1) and check if everything works fine 😉

Cheers!
Adrien

**Comment by hvaneylen** [comment]
Hi, Adrien,


After all, I can’t help but try even during my vacation to test snips so here is the result



D:\logiciels\python_ide\workspace\snips>pip install snips-nlu

Collecting snips-nlu

  Downloading https://files.pythonhosted.org/packages/0c/79/caf7e59fd8063a537418bfe9238e0f640146410ed7a9cf7872adc61b8d4e/snips_nlu-0.15.1-py2.py3-none-any.whl (82kB)

    100% |████████████████████████████████| 92kB 530kB/s

Requirement already satisfied: pathlib==1.0.1 in d:\logiciels\python\lib\site-packages (from snips-nlu)

Collecting snips-nlu-ontology==0.57.1 (from snips-nlu)

  Downloading https://files.pythonhosted.org/packages/62/22/976e218b1cfe9145008f003a56940631b5e42c5cfa87775680c17fbf1fac/snips_nlu_ontology-0.57.1.tar.gz

Requirement already satisfied: scikit-learn==0.19.1 in d:\logiciels\python\lib\site-packages (from snips-nlu)

Requirement already satisfied: num2words==0.5.6 in d:\logiciels\python\lib\site-packages (from snips-nlu)

Requirement already satisfied: scipy==1.0.0 in d:\logiciels\python\lib\site-packages (from snips-nlu)

Collecting snips-nlu-utils==0.6.1 (from snips-nlu)

  Downloading https://files.pythonhosted.org/packages/8b/08/9eddc4cd0e2606a58757a542da9346fae0f55d33a8cd6e0252201663d8f5/snips_nlu_utils-0.6.1-cp36-cp36m-win32.whl (392kB)

    100% |████████████████████████████████| 399kB 1.4MB/s

Requirement already satisfied: requests==2.18.4 in d:\logiciels\python\lib\site-packages (from snips-nlu)

Requirement already satisfied: sklearn-crfsuite==0.3.6 in d:\logiciels\python\lib\site-packages (from snips-nlu)

Collecting plac==0.9.6 (from snips-nlu)

  Downloading https://files.pythonhosted.org/packages/9e/9b/62c60d2f5bc135d2aa1d8c8a86aaf84edb719a59c7f11a4316259e61a298/plac-0.9.6-py2.py3-none-any.whl

Requirement already satisfied: semantic-version==2.6.0 in d:\logiciels\python\lib\site-packages (from snips-nlu)

Requirement already satisfied: enum34==1.1.6 in d:\logiciels\python\lib\site-packages (from snips-nlu)

Requirement already satisfied: numpy==1.14.0 in d:\logiciels\python\lib\site-packages (from snips-nlu)

Requirement already satisfied: future==0.16.0 in d:\logiciels\python\lib\site-packages (from snips-nlu-ontology==0.57.1->snips-nlu)

Requirement already satisfied: wheel==0.30.0 in d:\logiciels\python\lib\site-packages (from snips-nlu-ontology==0.57.1->snips-nlu)

Requirement already satisfied: idna<2.7,>=2.5 in d:\logiciels\python\lib\site-packages (from requests==2.18.4->snips-nlu)

Requirement already satisfied: chardet<3.1.0,>=3.0.2 in d:\logiciels\python\lib\site-packages (from requests==2.18.4->snips-nlu)

Requirement already satisfied: urllib3<1.23,>=1.21.1 in d:\logiciels\python\lib\site-packages (from requests==2.18.4->snips-nlu)

Requirement already satisfied: certifi>=2017.4.17 in d:\logiciels\python\lib\site-packages (from requests==2.18.4->snips-nlu)

Requirement already satisfied: python-crfsuite>=0.8.3 in d:\logiciels\python\lib\site-packages (from sklearn-crfsuite==0.3.6->snips-nlu)

Requirement already satisfied: tabulate in d:\logiciels\python\lib\site-packages (from sklearn-crfsuite==0.3.6->snips-nlu)

Requirement already satisfied: tqdm>=2.0 in d:\logiciels\python\lib\site-packages (from sklearn-crfsuite==0.3.6->snips-nlu)

Requirement already satisfied: six in d:\logiciels\python\lib\site-packages (from sklearn-crfsuite==0.3.6->snips-nlu)

Building wheels for collected packages: snips-nlu-ontology

  Running setup.py bdist_wheel for snips-nlu-ontology ... done

  Stored in directory: C:\Users\hvaneylen\AppData\Local\pip\Cache\wheels\b9\97\9a\c43bee110c4eb19b32e7fba317eb9c84abca1840e5d0309fe0

Successfully built snips-nlu-ontology

Installing collected packages: snips-nlu-ontology, snips-nlu-utils, plac, snips-nlu

  Found existing installation: snips-nlu-ontology 0.54.1

    Uninstalling snips-nlu-ontology-0.54.1:

      Successfully uninstalled snips-nlu-ontology-0.54.1

Successfully installed plac-0.9.6 snips-nlu-0.15.1 snips-nlu-ontology-0.57.1 snips-nlu-utils-0.6.1



YEAH ! this works now I need to install a language --  fr as I’m french

>python -m snips_nlu download fr  (I also try snips-nlu downlaod fr with the same result)

Traceback (most recent call last):

  File "D:\logiciels\python\lib\runpy.py", line 183, in _run_module_as_main

    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)

  File "D:\logiciels\python\lib\runpy.py", line 142, in _get_module_details

    return _get_module_details(pkg_main_name, error)

  File "D:\logiciels\python\lib\runpy.py", line 109, in _get_module_details

    __import__(pkg_name)

  File "D:\logiciels\python\lib\site-packages\snips_nlu\__init__.py", line 3, in <module>

    from snips_nlu_ontology import get_ontology_version

  File "D:\logiciels\python\lib\site-packages\snips_nlu_ontology\__init__.py", line 3, in <module>

    from snips_nlu_ontology.builtin_entities import (

  File "D:\logiciels\python\lib\site-packages\snips_nlu_ontology\builtin_entities.py", line 12, in <module>

    from snips_nlu_ontology.utils import (

  File "D:\logiciels\python\lib\site-packages\snips_nlu_ontology\utils.py", line 9, in <module>

    lib = cdll.LoadLibrary(dylib_path)

  File "D:\logiciels\python\lib\ctypes\__init__.py", line 422, in LoadLibrary

    return self._dlltype(name)

  File "D:\logiciels\python\lib\ctypes\__init__.py", line 344, in __init__

    self._handle = _dlopen(self._name, mode)

OSError: [WinError 193] %1 n’est pas une application Win32 valide



And during the installation, I have had a look on the quickstart and tutorial and the links to https://github.com/snipsco/snips-nlu/blob/master/samples/sample_dataset.json are broken.



So It’s near completion – If I can download the french language and have a look on the training files I can try to build a bot with snips.



Thanks for your help

Best Regards

Hugues



De : Adrien Ball <notifications@github.com>
Envoyé : lundi 9 juillet 2018 16:05
À : snipsco/snips-nlu <snips-nlu@noreply.github.com>
Cc : Hugues Van Eylen <hvaneylen@sodifrance.fr>; Mention <mention@noreply.github.com>
Objet : Re: [snipsco/snips-nlu] problem installing snips on windows (#549)


Hey @hvaneylen<https://github.com/hvaneylen> ,
I'm following up on this issue we now have pre-compiled wheels for the target win_amd64, for snips-nlu's dependencies, making the installation process on windows much faster/simpler.
It would be great, if you could try to install the latest version of snips-nlu (0.15.1) and check if everything works fine 😉

Cheers!
Adrien

**Comment by hvaneylen** [comment]
Hi Adrien,

Nope I’m running on Windows-64 actually.

De : Adrien Ball <notifications@github.com>
Envoyé : mercredi 11 juillet 2018 14:24
À : snipsco/snips-nlu <snips-nlu@noreply.github.com>
Cc : Hugues Van Eylen <hvaneylen@sodifrance.fr>; Mention <mention@noreply.github.com>
Objet : Re: [snipsco/snips-nlu] problem installing snips on windows (#549)


Hey @hvaneylen<https://github.com/hvaneylen> ,
From the logs, it seems that you are running on a Windows 32-bit, is that right?
We don't have yet Windows 32-bit wheels for snips-nlu-ontology so it is built from source on your machine in your case, and I suspect that what is built is a 64-bit dynamic library instead of 32-bit.
In order to try to fix this, as well as make the installation faster, I'm adding builds of win32 wheels in our Appveyor CI, so the next releases will contain the precompiled wheels.

--> snipsco/snips-nlu-utils#45<https://github.com/snipsco/snips-nlu-utils/pull/45>
--> snipsco/snips-nlu-ontology#73<https://github.com/snipsco/snips-nlu-ontology/pull/73>

**Comment by adrienball** [comment]
Ok, can you check that you have installed a 64bit of Python?
You can check it easily with:
`python -c "import struct;print(struct.calcsize('P') * 8)"`

**Comment by hvaneylen** [comment]
Hi Adrien,

Sorry for the delay but I lack the time to do all I want.
So good news – Effectively, I use a python 32
As I have anaconda 3 installed too (64) – I try it and succeed  (just a problem with Trend anti-virus which considered python as  a virus and threw it away :-(  so for a moment I considered Trend as a virus too ;-).


But the links on your site to https://github.com/snipsco/snips-nlu/blob/master/samples/sample_dataset.json are still broken.

Can I have a sample on training file ? in  order to try to use snips ?

Thx a lot
Best Regards
Hugues



De : Adrien Ball <notifications@github.com>
Envoyé : mercredi 11 juillet 2018 14:59
À : snipsco/snips-nlu <snips-nlu@noreply.github.com>
Cc : Hugues Van Eylen <hvaneylen@sodifrance.fr>; Mention <mention@noreply.github.com>
Objet : Re: [snipsco/snips-nlu] problem installing snips on windows (#549)


Ok, can you check that you have installed a 64bit of Python?
You can check it easily with:
python -c "import struct;print(struct.calcsize('P') * 8)"

**Comment by adrienball** [comment]
Glad to read this :)
Here is the correct link for the sample dataset --> https://github.com/snipsco/snips-nlu/blob/master/snips_nlu_samples/sample_dataset.json

Cheers

**Comment by adrienball** [comment]
Closing this as it seems resolved from what you said.
Feel free to open another issue, if you run into other troubles.
Thanks
